obserfy/obserfy

go.mod, go.sum, pkg/auth.go, pkg/curriculum.go, pkg/frontend.go, pkg/handler.go, pkg/helper.go, pkg/io.go, pkg/logger.go, pkg/main.go, pkg/observations.go, pkg/school.go, pkg/students.go, pkg/user.go
Error handling is now centralized and more robust.
=> ref(backend): Complete rewrite of error handling.

docker-compose.yml, docker/nginx/dev.dockerfile, docker/nginx/nginx.conf, docker/nginx/prod.dockerfile, pkg/main.go, pkg/postgres/authStore.go
Pass real IP address through nginx to be logged in go. Stop logging heartbeat calls. Fix nginx envsubst overwriting all variables.
=> ref(logging): Improve logging.

docker/nginx/prod.dockerfile
Nginx doesn't run properly on prod. Now prod.dockerfile is configured to mimic dev.
=> fix: Fix nginx prod.dockerfile.

.gitignore, apps/freyr/gatsby-config.js, apps/freyr/package.json, apps/freyr/src/components/button.tsx, apps/freyr/src/components/global.css, apps/freyr/src/components/header.tsx, apps/freyr/src/components/layout.tsx, apps/freyr/src/pages/404.tsx, apps/freyr/src/pages/contact.tsx, apps/freyr/src/pages/index.tsx, apps/freyr/src/pages/privacy-policy.tsx, yarn.lock
- Fixes #431. Now, parent portal is linked in the landing page.
- Partially finished #361 
- Linked privacy policy in landing page
=> Fix landing page contact form. Add missing links.

apps/freyr/src/components/header.tsx, apps/gaia/components/header.tsx, apps/gaia/pages/api/child/[childId].ts, apps/gaia/pages/api/children.ts, apps/gaia/pages/api/login.ts, apps/gaia/pages/api/me.ts, apps/gaia/utils/auth0.ts, apps/vor/pkg/postgres/guardianStore.go
- Avoid visiting `/` when user doesn't have session
- Protect all private API route with auth
- Use correct user email address.
=> Improve gaia login flow.

apps/gaia/components/header.tsx, apps/gaia/components/layout.tsx, apps/gaia/db/index.ts, apps/gaia/global.css, apps/gaia/pages/index.tsx, apps/gaia/utils/auth0.ts, docker/gaia/prod.dockerfile
- Add loading and parent state to parent portal
- Increase cookie lifetime to prevent user being forced to login continously
- Fix db connection not closed.
=> Add error and loading states to parent portal and some bugfixes.

apps/vor/pkg/class/test/lesson_plan_test.go, apps/vor/pkg/postgres/lessonplanStore.go
- Fix bug adding Repetition type of none causing an infinite loop.
- Add more test for post new plan endpoint.
=> test: Add test and bugfix for posting plans with repetition

apps/vor/pkg/imgproxy/imgproxy.go, apps/vor/pkg/main.go, apps/vor/pkg/minio/fileStorage.go, apps/vor/pkg/minio/imageStorage.go, apps/vor/pkg/minio/minio.go, apps/vor/pkg/postgres/postgres.go, apps/vor/pkg/postgres/schoolStore.go, apps/vor/pkg/school/school.go
- Some naming refactorings.
- Now minio client can be shared between fileStorage and imageStorage
=> ref: Refactor minio package to allow sharing minio.Client instances.

apps/vor/pkg/minio/fileStorage.go, apps/vor/pkg/postgres/fileStorage.go, apps/vor/pkg/postgres/postgres.go, apps/vor/pkg/postgres/schoolStore.go, apps/vor/pkg/school/school.go, apps/vor/pkg/school/store.go, apps/vor/pkg/school/test/file_test.go
- Add test for post-ing new file
- Post new file endpoint now correctly accepts a file
- Save file key on DB.
=> fix: Fix post new file endpoint.

renovate.json
=> ref: Improve renovate config.

apps/vor/frontend/src/api/students/usePatchStudentApi.ts, apps/vor/pkg/student/student.go, apps/vor/pkg/student/test/student_test.go
=> feat: update usePatchStudentApi to accept isActive parameter.

README.md, apps/vor/frontend/.storybook/preview.js
- Move box and flex import to theme-ui
- Add BASE_PATH mock (its gatsby's thing)
=> fix: Fix broken storybook build.

apps/vor/frontend/package.json
I don't think we use this for anything anymore.
=> chore(deps): Remove whatwg-fetch.

.circleci/config.yml, apps/e2e/cypress.json, apps/vor/pkg/minio/minio.go, docker-compose.yml, docker/postgres/postgresql.conf
CI now finishes in 7+ minutes, down from 11+ minutes.
=> ref: Speed up CI.

apps/vor/frontend/gatsby-browser.js, apps/vor/frontend/gatsby-config.js, apps/vor/frontend/graphql-types.ts, apps/vor/frontend/package.json, apps/vor/frontend/src/components/PageError/PageError.tsx, apps/vor/frontend/src/components/PageError/__snapshots__/PageError.test.tsx.snap, yarn.lock
- add bredcrumbs to sentry
- add user data to sentry
- use official sentry gatsby plugin
- connect error page to feedback page
=> fix: error reporting

apps/e2e/cypress/integration/pwa.spec.ts, apps/e2e/cypress/integration/vor-auth.spec.ts, apps/vor/frontend/graphql-types.ts, apps/vor/frontend/src/api/mailPasswordResetApi.ts, apps/vor/frontend/src/api/useGetInviteCodeDetails.ts, apps/vor/frontend/src/api/usePostLogin.ts, apps/vor/frontend/src/api/usePostRegister.ts, apps/vor/frontend/src/api/usePostResetPasswordEmail.ts, apps/vor/frontend/src/components/BrandBanner/BrandBanner.stories.tsx, apps/vor/frontend/src/components/BrandBanner/BrandBanner.test.tsx, apps/vor/frontend/src/components/BrandBanner/BrandBanner.tsx, apps/vor/frontend/src/components/BrandBanner/__snapshots__/BrandBanner.test.tsx.snap, apps/vor/frontend/src/components/EmptyClassDataPlaceholder/__snapshots__/EmptyClassDataPlaceholder.test.tsx.snap, apps/vor/frontend/src/components/InformationalCard/InformationalCard.tsx, apps/vor/frontend/src/components/InformationalCard/__snapshots__/InformationalCard.test.tsx.snap, apps/vor/frontend/src/components/PageForgotPassword/PageForgotPassword.tsx, apps/vor/frontend/src/components/PageForgotPassword/__snapshots__/PageForgotPassword.test.tsx.snap, apps/vor/frontend/src/components/PageLogin/PageLogin.tsx, apps/vor/frontend/src/components/PageLogin/__snapshots__/PageLogin.test.tsx.snap, apps/vor/frontend/src/components/PageRegister/PageRegister.tsx, apps/vor/frontend/src/components/PageRegister/__snapshots__/PageRegister.test.tsx.snap
Current vor's login, sign up and forgot password page can be confusing. Parents sometimes mistook it for parent portal because it doesn't say that this is for teachers only. This PR aims to fix this by:
- adding an "Obserfy for Teachers" banner
- adding an info card directing parents to parent portal
- compacting the overall design
- added loading indicator to sign up and loading page
- refactor login, register, and forgot password to use react-query, giving it conditional request, retries and "is loading" checks.
=> feat: revamped login, sign up and forgot password page.

apps/vor/frontend/src/api/students/useGetStudentPlans.ts, apps/vor/frontend/src/components/PageStudentPlans/PageStudentPlans.tsx, apps/vor/pkg/lessonplan/store.go, apps/vor/pkg/postgres/lessonplanStore.go, apps/vor/pkg/postgres/schoolStore.go, apps/vor/pkg/postgres/studentStore.go, apps/vor/pkg/school/school.go, apps/vor/pkg/school/store.go, apps/vor/pkg/student/student.go
=> add user name to /school/{schoolId}/plans

.circleci/config.yml, apps/vor/frontend/graphql-types.ts
=> improvement: deploy gaia from ci

apps/vor/frontend/graphql-types.ts, apps/vor/frontend/src/hooks/useLinkPreview.ts, apps/vor/pkg/lessonplan/lessonplan.go, apps/vor/pkg/lessonplan/store.go, apps/vor/pkg/postgres/lessonplanStore.go
=> Add auth middleware for lesson plan API

apps/vor/frontend/gatsby-config.js, apps/vor/frontend/graphql-types.ts
=> feat: cache /api on service worker

docker/nginx/nginx.conf
=> fix nginx error on image more than 1mb

.circleci/config.yml, apps/e2e/package.json, apps/vor/frontend/graphql-types.ts
- test gaia build
- run gaia on e2e
- improve ci job names
=> ref: Improve tests

apps/vor/frontend/graphql-types.ts, apps/vor/frontend/src/api/observations/usePostNewObservationImage.ts, apps/vor/frontend/src/components/ImagePreviewOverlay/ImagePreviewOverlay.tsx, apps/vor/frontend/src/components/Layout/Layout.tsx, apps/vor/frontend/src/components/Layout/__snapshots__/Layout.test.tsx.snap, apps/vor/frontend/src/components/PageCurriculumArea/PageCurriculumArea.tsx, apps/vor/frontend/src/components/PageStudentProfile/PageStudentProfile.stories.tsx, apps/vor/frontend/src/components/PageStudentProfile/PageStudentProfile.tsx, apps/vor/frontend/src/pages/dashboard/students/profile/index.tsx
Fix uploading an image on observation doesn't update react-query's cache with new data.
=> fix: uploading image doesn't update in memory cache

apps/freyr/tailwind.config.js, apps/gaia/.gitignore, apps/gaia/next.config.js, apps/gaia/package.json, apps/gaia/src/db/index.ts, yarn.lock
- also, implement service worker on gaia.
=> fix: fix student not showing when it doesn't have profile picture

apps/vor/frontend/i18n/lingui/en/messages.po, apps/vor/frontend/i18n/lingui/id/messages.po, apps/vor/frontend/src/components/DeleteClassDialog/DeleteClassDialog.tsx, apps/vor/frontend/src/components/DeleteCurriculumDialog/DeleteCurriculumDialog.tsx, apps/vor/frontend/src/components/DeleteSubjectDialog/DeleteSubjectDialog.tsx, apps/vor/frontend/src/components/DraggableMaterialListItem/DraggableMaterialListItem.tsx, apps/vor/frontend/src/components/EditCurriculumDialog/EditCurriculumDialog.tsx, apps/vor/frontend/src/components/NewAreaDialog/NewAreaDialog.tsx, apps/vor/frontend/src/components/PageCurriculumArea/PageCurriculumArea.tsx, apps/vor/frontend/src/components/PageEditClass/PageEditClass.tsx, apps/vor/frontend/src/components/PageEditStudentClass/PageEditStudentClass.tsx, apps/vor/frontend/src/components/PageEditSubject/PageEditSubject.tsx, apps/vor/frontend/src/components/PageNewStudentClass/PageNewStudentClass.tsx, apps/vor/frontend/src/components/PageNewSubject/PageNewSubject.tsx
fix the rest of missing translation in this issue https://github.com/obserfy/obserfy/issues/1382
=> fix missing translation

apps/vor/frontend/src/components/BackButton/__snapshots__/BackButton.test.tsx.snap, apps/vor/frontend/src/components/DatePickerDialog/DatePickerDialog.tsx, apps/vor/frontend/src/components/Dialog/Dialog.tsx, apps/vor/frontend/src/components/DialogHeader/__snapshots__/DialogHeader.test.tsx.snap, apps/vor/frontend/src/components/DraggableMaterialListItem/__snapshots__/DraggableMaterialListItem.test.tsx.snap, apps/vor/frontend/src/components/Layout/Layout.tsx, apps/vor/frontend/src/components/ObservationListItem/ObservationListItem.tsx, apps/vor/frontend/src/components/PageAddGuardian/__snapshots__/PageAddGuardian.test.tsx.snap, apps/vor/frontend/src/components/PageAllObservations/__snapshots__/PageAllObservations.test.tsx.snap, apps/vor/frontend/src/components/PageCurriculumArea/__snapshots__/PageCurriculumArea.test.tsx.snap, apps/vor/frontend/src/components/PageCurriculumSettings/__snapshots__/PageCurriculumSettings.test.tsx.snap, apps/vor/frontend/src/components/PageListOfGuardians/__snapshots__/PageListOfGuardians.test.tsx.snap, apps/vor/frontend/src/components/PageNewObservation/__snapshots__/PageNewObservation.test.tsx.snap, apps/vor/frontend/src/components/PageNewStudent/__snapshots__/PageNewStudent.test.tsx.snap, apps/vor/frontend/src/components/PageNewStudentAddGuardian/__snapshots__/PageNewStudentAddGuardian.test.tsx.snap, apps/vor/frontend/src/components/PageNewStudentPlans/__snapshots__/PageNewStudentPlans.test.tsx.snap, apps/vor/frontend/src/components/PageNewSubject/__snapshots__/PageNewSubject.test.tsx.snap, apps/vor/frontend/src/components/PageStudentImages/__snapshots__/PageStudentImages.test.tsx.snap, apps/vor/frontend/src/components/PageStudentOverview/DailyObservationCard.tsx, apps/vor/frontend/src/components/PageStudentOverview/__snapshots__/PageStudentOverview.test.tsx.snap, apps/vor/frontend/src/components/PageStudentPlanDetails/__snapshots__/PageStudentPlanDetails.test.tsx.snap, apps/vor/frontend/src/components/PageStudentPlans/__snapshots__/PageStudentPlans.test.tsx.snap, apps/vor/frontend/src/components/TopBar/__snapshots__/TopBar.test.tsx.snap, apps/vor/frontend/src/components/TopBarWithAction/__snapshots__/TopBarWithAction.test.tsx.snap, apps/vor/frontend/src/gatsby-plugin-theme-ui/index.ts
add the ability to jump directly to certain dates to find observations on page student overview.
=> feat: observation calendar selector

apps/vor/frontend/src/components/AlertDialog/AlertDialog.stories.tsx, apps/vor/frontend/src/components/AlertDialog/AlertDialog.tsx, apps/vor/frontend/src/components/DatePickerDialog/DatePickerDialog.tsx, apps/vor/frontend/src/components/DeleteStudentDialog/DeleteStudentDialog.tsx, apps/vor/frontend/src/components/PageAllObservations/ObservationsTable.tsx, apps/vor/frontend/src/components/PageAllObservations/PageAllObservations.tsx, apps/vor/frontend/src/components/PageAllObservations/__snapshots__/PageAllObservations.test.tsx.snap, apps/vor/frontend/src/components/PageObservationDetails/PageObservationDetails.tsx, apps/vor/frontend/src/components/PageStudentImageDetails/PageStudentImageDetails.tsx, apps/vor/frontend/src/components/PageStudentProfile/PageStudentProfile.tsx, apps/vor/frontend/src/components/StudentsList/StudentsList.tsx, apps/vor/frontend/src/hooks/api/useGetStudentObservations.ts, apps/vor/frontend/src/hooks/useDebounce.ts, apps/vor/frontend/src/pages/dashboard/admin/guardians/profile.tsx, apps/vor/frontend/src/pages/dashboard/students/profile/guardians/profile.tsx, apps/vor/go.mod, apps/vor/go.sum, apps/vor/pkg/main.go, apps/vor/pkg/observation/test/observation_test.go, apps/vor/pkg/postgres/studentStore.go, apps/vor/pkg/rest/csv.go, apps/vor/pkg/rest/error.go, apps/vor/pkg/rest/json.go, apps/vor/pkg/rest/rest.go, apps/vor/pkg/sentry.go, apps/vor/pkg/student/store.go, apps/vor/pkg/student/student.go, apps/vor/pkg/student/test/student_test.go, docker-compose.yml
- add the ability to search observations using keywords
- add date filtering
- fix JSON APIs returning plaintexts
=> feat: all observations filtering

apps/vor/frontend/src/components/Layout/Layout.tsx, apps/vor/frontend/src/components/Layout/__snapshots__/Layout.test.tsx.snap, apps/vor/frontend/src/components/PageSubscription/PageSubscription.tsx, apps/vor/frontend/src/components/PageSubscription/__snapshots__/PageSubscription.test.tsx.snap, apps/vor/go.sum
Clearly show loading state on subscription page to avoid confusing user on the state of their payment.
=> fix: improve UI issue on subscription page

apps/vor/frontend/i18n/lingui/en/messages.po, apps/vor/frontend/i18n/lingui/id/messages.po, apps/vor/frontend/src/components/Layout/Layout.tsx, apps/vor/frontend/src/components/PageNewStudent/NewStudentForm.tsx, apps/vor/frontend/src/components/PageNewStudent/NewStudentFormContext.tsx, apps/vor/frontend/src/components/PageNewStudent/PageNewStudent.tsx, apps/vor/frontend/src/components/PageNewStudentAddGuardian/PageNewStudentAddGuardian.tsx, apps/vor/frontend/src/components/PagePickGuardian/PagePickGuardian.tsx
=> ref: properly split NewStudentForm from the main bundle

apps/freyr/src/__generated__/gatsby-types.ts, apps/vor/frontend/src/__generated__/gatsby-schema.graphql, apps/vor/frontend/src/__generated__/gatsby-types.ts, apps/vor/frontend/src/components/PageCurriculumSettings/PageCurriculumSettings.tsx
Saving a new curriculum area was always failing because we passed the wrong ID
=> fix: saving area always failing.

README.md, apps/freyr/src/components/seo.tsx
Needs to know how much traffic we got.
=> feat(freyr): add anonymous analytics

.env.test, apps/e2e/cypress/integration/observation/crud.spec.ts, apps/e2e/cypress/integration/plans.spec.ts, apps/e2e/cypress/integration/students/profile.spec.ts, apps/freyr/src/__generated__/gatsby-types.ts, apps/vor/frontend/i18n/lingui/en/messages.po, apps/vor/frontend/i18n/lingui/id/messages.po, apps/vor/frontend/src/__generated__/gatsby-types.ts, apps/vor/frontend/src/components/MarkdownEditor/MarkdownEditor.stories.tsx, apps/vor/frontend/src/components/MarkdownEditor/MarkdownEditor.test.tsx, apps/vor/frontend/src/components/MarkdownEditor/MarkdownEditor.tsx, apps/vor/frontend/src/components/MarkdownEditor/__snapshots__/MarkdownEditor.test.tsx.snap, apps/vor/frontend/src/components/PageAllObservations/__snapshots__/PageAllObservations.test.tsx.snap, apps/vor/frontend/src/components/PageCurriculumMaterial/DescriptionEditor.tsx, apps/vor/frontend/src/components/PageNewObservation/PageNewObservation.tsx, apps/vor/frontend/src/components/PageNewObservation/__snapshots__/PageNewObservation.test.tsx.snap, apps/vor/frontend/src/components/PageNewStudentPlans/PageNewStudentPlans.tsx, apps/vor/frontend/src/components/PageNewStudentPlans/__snapshots__/PageNewStudentPlans.test.tsx.snap, apps/vor/frontend/src/components/PageObservationDetails/DetailsCard.tsx, apps/vor/frontend/src/components/PageObservationDetails/PageObservationDetails.tsx, apps/vor/frontend/src/components/PageStudentPlanDetails/LessonPlanDescriptionCard.tsx, apps/vor/frontend/src/components/PageStudentPlanDetails/PageStudentPlanDetails.tsx, apps/vor/frontend/src/components/PageStudentPlanDetails/__snapshots__/PageStudentPlanDetails.test.tsx.snap, apps/vor/frontend/src/components/PageStudentPlans/PageStudentPlans.tsx, apps/vor/frontend/src/components/PageStudentPlans/__snapshots__/PageStudentPlans.test.tsx.snap, apps/vor/frontend/src/components/TranslucentBar/TranslucentBar.tsx, apps/vor/frontend/src/gatsby-plugin-theme-ui/index.ts, apps/vor/frontend/src/hooks/api/useGetStudentMaterialProgress.ts, apps/vor/frontend/src/test-utils.tsx
Start using the new markdown editor in other places.
=> feat: Better markdown editor.

packages/obserfy-db/.env, packages/obserfy-db/README.md, packages/obserfy-db/package.json, packages/obserfy-db/prisma/schema.prisma, yarn.lock
We could potentially unify our data access layer across testing, vor, and gaia into one package through prisma.
=> feat: try prisma on its own package.

apps/vor/frontend/src/__generated__/models.ts, apps/vor/frontend/src/hooks/api/reports/useGetProgressReport.ts, apps/vor/frontend/src/hooks/api/reports/usePatchReport.ts, apps/vor/frontend/src/hooks/api/reports/usePostReportPublished.ts, apps/vor/frontend/src/pages/dashboard/reports/manage/index.tsx, apps/vor/pkg/domain/model.go, apps/vor/pkg/postgres/progress_reports_store.go, apps/vor/pkg/reports/progress_reports.go
=> feat: publish report

apps/vor/frontend/i18n/lingui/en/messages.po, apps/vor/frontend/i18n/lingui/id/messages.po, apps/vor/pkg/main.go, apps/vor/pkg/postgres/progress_reports_store.go, apps/vor/pkg/progress_report/progress_reports.go, apps/vor/pkg/progress_report/test/progress_reports_test.go, apps/vor/pkg/reports/progress_reports.go, apps/vor/pkg/school/test/report_test.go
=> fix: protect report route with middleware

apps/vor/frontend/src/pages/dashboard/reports/manage/index.tsx, apps/vor/frontend/src/pages/dashboard/reports/manage/student/index.tsx
- resolves OBS-55
- resolves OBS-54
=> fix: show student report indicator and fix general comments obstructed on mobile

apps/gaia/src/pages/_app.tsx, apps/vor/frontend/i18n/lingui/en/messages.po, apps/vor/frontend/i18n/lingui/id/messages.po, apps/vor/frontend/src/__generated__/models.ts, apps/vor/frontend/src/components/EditReportSideBar/EditReportSideBar.stories.tsx, apps/vor/frontend/src/components/EditReportSideBar/EditReportSideBar.test.tsx, apps/vor/frontend/src/components/EditReportSideBar/EditReportSideBar.tsx, apps/vor/frontend/src/components/EditReportSideBar/__snapshots__/EditReportSideBar.test.tsx.snap, apps/vor/frontend/src/components/PageCurriculumSubject/PageCurriculumSubject.tsx, apps/vor/frontend/src/components/PageNewReport/PageNewReport.tsx, apps/vor/frontend/src/components/PageNewStudent/__snapshots__/PageNewStudent.test.tsx.snap, apps/vor/frontend/src/components/PageStudentOverview/AssessmentCard.tsx, apps/vor/frontend/src/components/PageStudentOverview/PageStudentOverview.tsx, apps/vor/frontend/src/components/StudentMaterialProgressDialog/StudentMaterialProgressDialog.tsx, apps/vor/frontend/src/components/StudentPicturePlaceholder/StudentPicturePlaceholder.tsx, apps/vor/frontend/src/gatsby-plugin-theme-ui/colors.ts, apps/vor/frontend/src/hooks/api/reports/useDeleteReport.ts, apps/vor/frontend/src/hooks/api/reports/useGetProgressReport.ts, apps/vor/frontend/src/hooks/api/reports/usePatchReport.ts, apps/vor/frontend/src/hooks/api/schools/useGetSchool.ts, apps/vor/frontend/src/hooks/api/students/usePatchAssessments.ts, apps/vor/frontend/src/hooks/api/students/usePatchStudentMaterialProgress.ts, apps/vor/frontend/src/hooks/api/useGetProgressReports.ts, apps/vor/frontend/src/icons/edit.svg, apps/vor/frontend/src/layouts/index.tsx, apps/vor/frontend/src/pages/dashboard/reports/manage/index.tsx, apps/vor/pkg/postgres/progress_reports_store.go, apps/vor/pkg/progress_report/progress_reports.go
=> feat: delete and edit report
